name: orogconv
channels:
 - defaults
 - conda-forge
dependencies:
 - cartopy=0.18.0
 - jupyter
 - matplotlib=3.3.2
 - numpy=1.19.2
 - python=3.7.9
 - scipy=1.5.2
 - xarray=0.16.2
 - netcdf4=1.5.7
 - metpy=0.12.2
